// Code generated by mockery v2.46.3. DO NOT EDIT.

package handlersmocks

import (
	context "context"

	credentialsv1 "buf.build/gen/go/a-novel/proto/protocolbuffers/go/credentials/v1"

	mock "github.com/stretchr/testify/mock"
)

// MockCreateCredentials is an autogenerated mock type for the CreateCredentials type
type MockCreateCredentials struct {
	mock.Mock
}

type MockCreateCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateCredentials) EXPECT() *MockCreateCredentials_Expecter {
	return &MockCreateCredentials_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: _a0, _a1
func (_m *MockCreateCredentials) Exec(_a0 context.Context, _a1 *credentialsv1.CreateServiceExecRequest) (*credentialsv1.CreateServiceExecResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *credentialsv1.CreateServiceExecResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *credentialsv1.CreateServiceExecRequest) (*credentialsv1.CreateServiceExecResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *credentialsv1.CreateServiceExecRequest) *credentialsv1.CreateServiceExecResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentialsv1.CreateServiceExecResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *credentialsv1.CreateServiceExecRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateCredentials_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCreateCredentials_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *credentialsv1.CreateServiceExecRequest
func (_e *MockCreateCredentials_Expecter) Exec(_a0 interface{}, _a1 interface{}) *MockCreateCredentials_Exec_Call {
	return &MockCreateCredentials_Exec_Call{Call: _e.mock.On("Exec", _a0, _a1)}
}

func (_c *MockCreateCredentials_Exec_Call) Run(run func(_a0 context.Context, _a1 *credentialsv1.CreateServiceExecRequest)) *MockCreateCredentials_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*credentialsv1.CreateServiceExecRequest))
	})
	return _c
}

func (_c *MockCreateCredentials_Exec_Call) Return(_a0 *credentialsv1.CreateServiceExecResponse, _a1 error) *MockCreateCredentials_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateCredentials_Exec_Call) RunAndReturn(run func(context.Context, *credentialsv1.CreateServiceExecRequest) (*credentialsv1.CreateServiceExecResponse, error)) *MockCreateCredentials_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateCredentials creates a new instance of MockCreateCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateCredentials {
	mock := &MockCreateCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
