// Code generated by mockery v2.46.3. DO NOT EDIT.

package handlersmocks

import (
	context "context"

	credentialsv1 "buf.build/gen/go/a-novel/proto/protocolbuffers/go/credentials/v1"

	mock "github.com/stretchr/testify/mock"
)

// MockGetCredentials is an autogenerated mock type for the GetCredentials type
type MockGetCredentials struct {
	mock.Mock
}

type MockGetCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetCredentials) EXPECT() *MockGetCredentials_Expecter {
	return &MockGetCredentials_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: _a0, _a1
func (_m *MockGetCredentials) Exec(_a0 context.Context, _a1 *credentialsv1.GetServiceExecRequest) (*credentialsv1.GetServiceExecResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *credentialsv1.GetServiceExecResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *credentialsv1.GetServiceExecRequest) (*credentialsv1.GetServiceExecResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *credentialsv1.GetServiceExecRequest) *credentialsv1.GetServiceExecResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentialsv1.GetServiceExecResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *credentialsv1.GetServiceExecRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetCredentials_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGetCredentials_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *credentialsv1.GetServiceExecRequest
func (_e *MockGetCredentials_Expecter) Exec(_a0 interface{}, _a1 interface{}) *MockGetCredentials_Exec_Call {
	return &MockGetCredentials_Exec_Call{Call: _e.mock.On("Exec", _a0, _a1)}
}

func (_c *MockGetCredentials_Exec_Call) Run(run func(_a0 context.Context, _a1 *credentialsv1.GetServiceExecRequest)) *MockGetCredentials_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*credentialsv1.GetServiceExecRequest))
	})
	return _c
}

func (_c *MockGetCredentials_Exec_Call) Return(_a0 *credentialsv1.GetServiceExecResponse, _a1 error) *MockGetCredentials_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetCredentials_Exec_Call) RunAndReturn(run func(context.Context, *credentialsv1.GetServiceExecRequest) (*credentialsv1.GetServiceExecResponse, error)) *MockGetCredentials_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetCredentials creates a new instance of MockGetCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCredentials {
	mock := &MockGetCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
