// Code generated by mockery v2.46.3. DO NOT EDIT.

package handlersmocks

import (
	context "context"

	credentialsv1 "buf.build/gen/go/a-novel/proto/protocolbuffers/go/credentials/v1"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateCredentials is an autogenerated mock type for the UpdateCredentials type
type MockUpdateCredentials struct {
	mock.Mock
}

type MockUpdateCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateCredentials) EXPECT() *MockUpdateCredentials_Expecter {
	return &MockUpdateCredentials_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: _a0, _a1
func (_m *MockUpdateCredentials) Exec(_a0 context.Context, _a1 *credentialsv1.UpdateServiceExecRequest) (*credentialsv1.UpdateServiceExecResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *credentialsv1.UpdateServiceExecResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *credentialsv1.UpdateServiceExecRequest) (*credentialsv1.UpdateServiceExecResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *credentialsv1.UpdateServiceExecRequest) *credentialsv1.UpdateServiceExecResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentialsv1.UpdateServiceExecResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *credentialsv1.UpdateServiceExecRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateCredentials_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockUpdateCredentials_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *credentialsv1.UpdateServiceExecRequest
func (_e *MockUpdateCredentials_Expecter) Exec(_a0 interface{}, _a1 interface{}) *MockUpdateCredentials_Exec_Call {
	return &MockUpdateCredentials_Exec_Call{Call: _e.mock.On("Exec", _a0, _a1)}
}

func (_c *MockUpdateCredentials_Exec_Call) Run(run func(_a0 context.Context, _a1 *credentialsv1.UpdateServiceExecRequest)) *MockUpdateCredentials_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*credentialsv1.UpdateServiceExecRequest))
	})
	return _c
}

func (_c *MockUpdateCredentials_Exec_Call) Return(_a0 *credentialsv1.UpdateServiceExecResponse, _a1 error) *MockUpdateCredentials_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateCredentials_Exec_Call) RunAndReturn(run func(context.Context, *credentialsv1.UpdateServiceExecRequest) (*credentialsv1.UpdateServiceExecResponse, error)) *MockUpdateCredentials_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateCredentials creates a new instance of MockUpdateCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateCredentials {
	mock := &MockUpdateCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
