// Code generated by mockery v2.46.3. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	services "github.com/a-novel/uservice-credentials/pkg/services"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdateCredentials is an autogenerated mock type for the UpdateCredentials type
type MockUpdateCredentials struct {
	mock.Mock
}

type MockUpdateCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateCredentials) EXPECT() *MockUpdateCredentials_Expecter {
	return &MockUpdateCredentials_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, data
func (_m *MockUpdateCredentials) Exec(ctx context.Context, data *services.UpdateCredentialsRequest) (*services.UpdateCredentialsResponse, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.UpdateCredentialsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *services.UpdateCredentialsRequest) (*services.UpdateCredentialsResponse, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *services.UpdateCredentialsRequest) *services.UpdateCredentialsResponse); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.UpdateCredentialsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *services.UpdateCredentialsRequest) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateCredentials_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockUpdateCredentials_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - data *services.UpdateCredentialsRequest
func (_e *MockUpdateCredentials_Expecter) Exec(ctx interface{}, data interface{}) *MockUpdateCredentials_Exec_Call {
	return &MockUpdateCredentials_Exec_Call{Call: _e.mock.On("Exec", ctx, data)}
}

func (_c *MockUpdateCredentials_Exec_Call) Run(run func(ctx context.Context, data *services.UpdateCredentialsRequest)) *MockUpdateCredentials_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*services.UpdateCredentialsRequest))
	})
	return _c
}

func (_c *MockUpdateCredentials_Exec_Call) Return(_a0 *services.UpdateCredentialsResponse, _a1 error) *MockUpdateCredentials_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateCredentials_Exec_Call) RunAndReturn(run func(context.Context, *services.UpdateCredentialsRequest) (*services.UpdateCredentialsResponse, error)) *MockUpdateCredentials_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateCredentials creates a new instance of MockUpdateCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateCredentials {
	mock := &MockUpdateCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
