// Code generated by mockery v2.46.3. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/a-novel/uservice-credentials/pkg/dao"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSearchCredentials is an autogenerated mock type for the SearchCredentials type
type MockSearchCredentials struct {
	mock.Mock
}

type MockSearchCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchCredentials) EXPECT() *MockSearchCredentials_Expecter {
	return &MockSearchCredentials_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, request
func (_m *MockSearchCredentials) Exec(ctx context.Context, request *dao.SearchCredentialsRequest) (uuid.UUIDs, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 uuid.UUIDs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dao.SearchCredentialsRequest) (uuid.UUIDs, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dao.SearchCredentialsRequest) uuid.UUIDs); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUIDs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dao.SearchCredentialsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchCredentials_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockSearchCredentials_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.SearchCredentialsRequest
func (_e *MockSearchCredentials_Expecter) Exec(ctx interface{}, request interface{}) *MockSearchCredentials_Exec_Call {
	return &MockSearchCredentials_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockSearchCredentials_Exec_Call) Run(run func(ctx context.Context, request *dao.SearchCredentialsRequest)) *MockSearchCredentials_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dao.SearchCredentialsRequest))
	})
	return _c
}

func (_c *MockSearchCredentials_Exec_Call) Return(_a0 uuid.UUIDs, _a1 error) *MockSearchCredentials_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchCredentials_Exec_Call) RunAndReturn(run func(context.Context, *dao.SearchCredentialsRequest) (uuid.UUIDs, error)) *MockSearchCredentials_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchCredentials creates a new instance of MockSearchCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchCredentials {
	mock := &MockSearchCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
