// Code generated by mockery v2.46.3. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/a-novel/uservice-credentials/pkg/dao"
	mock "github.com/stretchr/testify/mock"
)

// MockExistsCredentials is an autogenerated mock type for the ExistsCredentials type
type MockExistsCredentials struct {
	mock.Mock
}

type MockExistsCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExistsCredentials) EXPECT() *MockExistsCredentials_Expecter {
	return &MockExistsCredentials_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, request
func (_m *MockExistsCredentials) Exec(ctx context.Context, request *dao.ExistsCredentialsRequest) (bool, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dao.ExistsCredentialsRequest) (bool, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dao.ExistsCredentialsRequest) bool); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dao.ExistsCredentialsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExistsCredentials_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockExistsCredentials_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ExistsCredentialsRequest
func (_e *MockExistsCredentials_Expecter) Exec(ctx interface{}, request interface{}) *MockExistsCredentials_Exec_Call {
	return &MockExistsCredentials_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockExistsCredentials_Exec_Call) Run(run func(ctx context.Context, request *dao.ExistsCredentialsRequest)) *MockExistsCredentials_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dao.ExistsCredentialsRequest))
	})
	return _c
}

func (_c *MockExistsCredentials_Exec_Call) Return(_a0 bool, _a1 error) *MockExistsCredentials_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExistsCredentials_Exec_Call) RunAndReturn(run func(context.Context, *dao.ExistsCredentialsRequest) (bool, error)) *MockExistsCredentials_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExistsCredentials creates a new instance of MockExistsCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExistsCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExistsCredentials {
	mock := &MockExistsCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
